name: Report to Xeel
on:
  push:
    branches: [main]
  schedule:
    - cron: '45 8 * * *'
permissions:
  id-token: write
  contents: read
  packages: read
jobs:
  dependency-debt:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm build
      - run: pnpm add @xeel-dev/cli
      - run: npx xeel plugins link
      - run: node ./src/npm/package-manager/__tests__/run-e2e-setup.js
      - run: npx xeel version-debt report -r "$GITHUB_REPOSITORY_ID" --auth github --organization "x::org:64jlQszyh97h4u4d0IGc7J"
        env:
          XEEL_API: 'https://api.xeel-dev.com' # Use the development API
          XEEL_APP: 'https://app.xeel-dev.com' # Use the development APP
